### ISSUE TITLE
Book-Tesla | Kanban board review

### ISSUE THREAD

**Issue by lu-jim** [lu-jim/book-tesla#15]
##  Repos for the Book Tesla project:
- Front-end: https://github.com/Maclenn77/book-tesla-frontend
- Back-end: https://github.com/lu-jim/book-tesla

## Members:
- @Maclenn77 
- @lu-jim 
- @iammouaz ( He has been busy, so we are waiting for him to join the repo).

## Screenshot:
![image](https://user-images.githubusercontent.com/59420634/162259861-0a8aec99-8cf7-4f9f-acbb-6adbf390118c.png)

**Comment by MuriloRoque** [comment]
Hi @lu-jim, @Maclenn77,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
